### ISSUE TITLE
option -k and -t

### ISSUE THREAD

**Issue by hetica** [jaudoux/countTags#1]
Options `-k` and `-t` are not correctly writing with --help:

```
countTags --help
countTags
USAGE: countTags [options] tags.fa seq.fastq[.gz]

Options:
  --help          Print usage and exit.
  -k=INT          tags length
  -m=INT          max number of reads
  -t=INT          number of threads
  --stranded      strand-specific protocol
  --normalize     normalize counts
  --tag-names     print tag names in the output
  --merge-counts  merge counts from all input FASTQs
```

`-k=32` doesn't works but `-k 32`, `-k32` and `--k=32` seems  ok.
It is the same issue whith `-t` option, but multithreading doesn't works for me (should be removes this option ?)

**Comment by jaudoux** [comment]
Yes the helper is not right. This is fixed (commit https://github.com/jaudoux/countTags/commit/38fb7bdc9d6f63d6bbfe0579e28d84296f37e565). For the NB_THREADS option, it was linked to nothing into the code, I did not had the time to parrallelize countTags yet...
